name: Publish

on:
  push:
    branches:
      - gh-pages

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Authenticate with NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build
        run: npm run build
      - name: Commit build
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github@example.com"
          CHANGED=$(git diff-index --name-only HEAD -- assets/main.js)
          if [ -n "$CHANGED" ]; then
              git add assets/main.js
              git commit -m "build: update JavaScript build"
              git push
          fi
